### ISSUE TITLE
您好，能不能谈一谈百度前端题21题

### ISSUE THREAD

**Issue by renxiaopeng13579** [HeyJax/heyjax.github.io#1]
`this.getData = function() {
      switch (input) {
        case 'tag':
          var value = this.input.value.match(/^[^,\， ]*/)[0];
          break;
        case 'hobby':
        default:
          var value = this.input.value.trim().split(/,|，|、|\s|\n|\r|\t/);
      }
      return value;
    };`
Tag的筛选`.match(/^^,\， ]*/)`正则 如何理解。感觉你写的好繁琐

**Comment by StevenYuysy** [comment]
## tag 要求

要求遇到用户输入空格，逗号，回车时，都自动把当前输入的内容作为一个tag放在输入框下面。
Tag不能有重复的，遇到重复输入的Tag，自动忽视。
每个Tag请做trim处理

## 对应处理

正常来讲，我们监听键盘 keyup 事件的时候，如果用户输入过快，会导致 keyup 监听完以后，data 的数值超过一个，或者里面包含有空格，逗号，这是我们不想发生的，于是每一次 keyup 事件监听完以后，我们都需要对获取的这个 data 作一个处理，这里用正则分隔开。

``` JavaScript
this.input.value.match(/(^[^,\， ]*)/)
```

这个正则的意思是，中括号里面匹配了三个东西，英文逗号，中文逗号和空格，也就是说以这三个东西结尾的第一个数组都会被匹配出来。

请问这样清楚了吗？
